
package ventana.prueba;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


//librerias 


import java.io.*;


/**
 *
 * @author david
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null); //lo deja en la mitad
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Registar_N = new javax.swing.JButton();
        Modificar_N = new javax.swing.JButton();
        Id_Negocio = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Descripción = new javax.swing.JTextField();
        F_Inicio = new javax.swing.JFormattedTextField();
        F_Final = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Registro1 = new javax.swing.JLabel();
        AsignarObligaciones = new javax.swing.JPanel();
        Descripcion_o = new javax.swing.JTextField();
        Registar_O = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Fecha_Vencimiento = new javax.swing.JFormattedTextField();
        Monto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        VerTabla = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Registro2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        AsignarObligaciones1 = new javax.swing.JPanel();
        Nombre_p = new javax.swing.JTextField();
        Registar_O1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Apellido_p = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        VerTabla1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Registro3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TipoDoc = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        NumID = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Id_Fidu = new javax.swing.JFormattedTextField();
        TipoDoc1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ApellidoConsulta = new javax.swing.JTextField();
        Buscar_Obligacion = new javax.swing.JButton();
        Nombre_Consulta1 = new javax.swing.JTextField();
        Des_Obligacion = new javax.swing.JTextField();
        Nombre_Consulta3 = new javax.swing.JTextField();
        NumID2 = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        AñadirObligacion = new javax.swing.JButton();
        Estado_Añadir1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Buscar_Fidu2 = new javax.swing.JButton();
        Id_Obligacion = new javax.swing.JFormattedTextField();
        Nombre_Consulta5 = new javax.swing.JTextField();
        Estado_Añadir2 = new javax.swing.JLabel();
        Id_Fidu2 = new javax.swing.JFormattedTextField();
        Nombre_Consulta6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Nombre_Consulta7 = new javax.swing.JTextField();
        AñadirNegocioPersona1 = new javax.swing.JButton();
        BuscarNegocios = new javax.swing.JButton();
        Buscar_Fidu3 = new javax.swing.JButton();
        GuardarExcel = new javax.swing.JButton();
        GuardarDoc = new javax.swing.JComboBox<>();
        GuardarNum = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registar_N.setText("Registrar");
        Registar_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registar_NActionPerformed(evt);
            }
        });
        jPanel4.add(Registar_N, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 77, -1, -1));

        Modificar_N.setText("Ver Data Base");
        Modificar_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_NActionPerformed(evt);
            }
        });
        jPanel4.add(Modificar_N, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 77, -1, -1));

        Id_Negocio.setText("10");
        Id_Negocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_NegocioActionPerformed(evt);
            }
        });
        jPanel4.add(Id_Negocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 24, 101, -1));

        Nombre.setText("Nombre");
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanel4.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 24, 162, -1));

        Descripción.setText("Descripcion");
        Descripción.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripciónActionPerformed(evt);
            }
        });
        jPanel4.add(Descripción, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 24, 163, -1));

        F_Inicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("y/MM/d"))));
        F_Inicio.setText("2025/01/28");
        F_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_InicioActionPerformed(evt);
            }
        });
        jPanel4.add(F_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 24, 126, -1));

        F_Final.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("y/MM/d"))));
        F_Final.setText("2025/01/30");
        F_Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_FinalActionPerformed(evt);
            }
        });
        jPanel4.add(F_Final, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 24, 126, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id_Negocio_Fiduciario", "Nombre", "Descripción", "Fecha de inicio", "Fecha de fin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 600, 408));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 118, -1, -1));

        jLabel1.setText("ID Negocio");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 6, -1, -1));

        jLabel2.setText("Descripcion");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 6, 79, -1));

        jLabel3.setText("Nombre");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 6, -1, -1));

        jLabel4.setText("Fecha Inicio (aa/mm/dd)");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 6, 134, -1));

        jLabel5.setText("Fecha final (aa/mm/dd)");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 6, -1, -1));

        Registro1.setText("Status");
        jPanel4.add(Registro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Asignar Varios Negocios", jPanel2);

        AsignarObligaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Descripcion_o.setText("Obligacion n");
        Descripcion_o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Descripcion_oActionPerformed(evt);
            }
        });
        AsignarObligaciones.add(Descripcion_o, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 24, 193, -1));

        Registar_O.setText("Registrar");
        Registar_O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registar_OActionPerformed(evt);
            }
        });
        AsignarObligaciones.add(Registar_O, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 52, -1, -1));

        jLabel8.setText("Descripcion");
        AsignarObligaciones.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 27, -1, -1));

        Fecha_Vencimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("y/MM/d"))));
        Fecha_Vencimiento.setText("2025/01/28");
        Fecha_Vencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fecha_VencimientoActionPerformed(evt);
            }
        });
        AsignarObligaciones.add(Fecha_Vencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 24, 126, -1));

        Monto.setText("1000.05");
        Monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoActionPerformed(evt);
            }
        });
        AsignarObligaciones.add(Monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 52, 193, -1));

        jLabel6.setText("Auto (Ide)");
        AsignarObligaciones.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 27, -1, -1));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id_Negocio_Fiduciario", "Descripción", "Monto", "Fecha de vencimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 638, 346));

        AsignarObligaciones.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 162, -1, -1));

        VerTabla.setText("Ver Data Base");
        VerTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerTablaActionPerformed(evt);
            }
        });
        AsignarObligaciones.add(VerTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 93, -1, -1));

        jLabel10.setText("Fecha Vencimiento (aa/mm/dd)");
        AsignarObligaciones.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 27, -1, -1));

        Registro2.setText("Status");
        AsignarObligaciones.add(Registro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 96, -1, -1));

        jLabel9.setText("Monto");
        AsignarObligaciones.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 55, -1, -1));

        jTabbedPane1.addTab("Asignar Varias Obligaciones", AsignarObligaciones);

        AsignarObligaciones1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre_p.setText("David");
        Nombre_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_pActionPerformed(evt);
            }
        });
        AsignarObligaciones1.add(Nombre_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 24, 177, -1));

        Registar_O1.setText("Registrar");
        Registar_O1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registar_O1ActionPerformed(evt);
            }
        });
        AsignarObligaciones1.add(Registar_O1, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 92, -1, -1));

        jLabel11.setText("Nombre");
        AsignarObligaciones1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 27, -1, -1));

        Apellido_p.setText("Duarte");
        Apellido_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido_pActionPerformed(evt);
            }
        });
        AsignarObligaciones1.add(Apellido_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 52, 177, -1));

        jLabel7.setText("Auto (Ide)");
        AsignarObligaciones1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 27, -1, -1));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Persona", "Nombre", "Apellido", "Tipo Documento", "Numero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 638, 346));

        AsignarObligaciones1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 158, -1, -1));

        VerTabla1.setText("Ver Data Base");
        VerTabla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerTabla1ActionPerformed(evt);
            }
        });
        AsignarObligaciones1.add(VerTabla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 125, -1, -1));

        jLabel12.setText("Tipo de documento");
        AsignarObligaciones1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 27, -1, -1));

        Registro3.setText("Status");
        AsignarObligaciones1.add(Registro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 92, -1, -1));

        jLabel13.setText("Apellido");
        AsignarObligaciones1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 55, -1, -1));

        TipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "TI", "NIT", "PASAPORTE" }));
        TipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDocActionPerformed(evt);
            }
        });
        AsignarObligaciones1.add(TipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 24, -1, -1));

        jLabel14.setText("Numero");
        AsignarObligaciones1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 55, -1, -1));

        NumID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        NumID.setText("100001");
        NumID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumIDActionPerformed(evt);
            }
        });
        AsignarObligaciones1.add(NumID, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 52, 98, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AsignarObligaciones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AsignarObligaciones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Asignar Participantes", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Esta seccion permite agregar Varios Obligaciones a un Negocio Fiduciario");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 700, -1));

        Id_Fidu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Id_Fidu.setText("1");
        Id_Fidu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_FiduActionPerformed(evt);
            }
        });
        jPanel3.add(Id_Fidu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 98, -1));

        TipoDoc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "TI", "NIT", "PASAPORTE" }));
        TipoDoc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDoc1ActionPerformed(evt);
            }
        });
        jPanel3.add(TipoDoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel16.setText("Numero");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel17.setText("Id");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        ApellidoConsulta.setEditable(false);
        ApellidoConsulta.setBackground(new java.awt.Color(255, 255, 255));
        ApellidoConsulta.setText("Apellido");
        ApellidoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoConsultaActionPerformed(evt);
            }
        });
        jPanel3.add(ApellidoConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, -1));

        Buscar_Obligacion.setText("Buscar Obligacion");
        Buscar_Obligacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_ObligacionActionPerformed(evt);
            }
        });
        jPanel3.add(Buscar_Obligacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 180, -1));

        Nombre_Consulta1.setEditable(false);
        Nombre_Consulta1.setBackground(new java.awt.Color(255, 255, 255));
        Nombre_Consulta1.setText("Nombre");
        jPanel3.add(Nombre_Consulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 100, -1));

        Des_Obligacion.setEditable(false);
        Des_Obligacion.setBackground(new java.awt.Color(255, 255, 255));
        Des_Obligacion.setText("Descripcion");
        Des_Obligacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Des_ObligacionActionPerformed(evt);
            }
        });
        jPanel3.add(Des_Obligacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 170, 50));

        Nombre_Consulta3.setEditable(false);
        Nombre_Consulta3.setBackground(new java.awt.Color(255, 255, 255));
        Nombre_Consulta3.setText("Nombre");
        jPanel3.add(Nombre_Consulta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, -1));

        NumID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        NumID2.setText("100001");
        NumID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumID2ActionPerformed(evt);
            }
        });
        jPanel3.add(NumID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 98, -1));

        jLabel18.setText("Documento");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        AñadirObligacion.setText("Añadir");
        AñadirObligacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirObligacionActionPerformed(evt);
            }
        });
        jPanel3.add(AñadirObligacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        Estado_Añadir1.setText("Estado");
        jPanel3.add(Estado_Añadir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        jLabel19.setText("Esta seccion permite agregar Varios Negocios Fiduciarios a una persona");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 700, -1));

        Buscar_Fidu2.setText("Buscar Negocios Inscritos");
        Buscar_Fidu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_Fidu2ActionPerformed(evt);
            }
        });
        jPanel3.add(Buscar_Fidu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, -1));

        Id_Obligacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Id_Obligacion.setText("1");
        Id_Obligacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_ObligacionActionPerformed(evt);
            }
        });
        jPanel3.add(Id_Obligacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 98, -1));

        Nombre_Consulta5.setEditable(false);
        Nombre_Consulta5.setBackground(new java.awt.Color(255, 255, 255));
        Nombre_Consulta5.setText("Descripcion");
        jPanel3.add(Nombre_Consulta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 170, 50));

        Estado_Añadir2.setText("Estado");
        jPanel3.add(Estado_Añadir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        Id_Fidu2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Id_Fidu2.setText("1");
        Id_Fidu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_Fidu2ActionPerformed(evt);
            }
        });
        jPanel3.add(Id_Fidu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 98, -1));

        Nombre_Consulta6.setEditable(false);
        Nombre_Consulta6.setBackground(new java.awt.Color(255, 255, 255));
        Nombre_Consulta6.setText("Nombre");
        jPanel3.add(Nombre_Consulta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 100, -1));

        jLabel21.setText("Id");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        jLabel22.setText("Id");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        Nombre_Consulta7.setEditable(false);
        Nombre_Consulta7.setBackground(new java.awt.Color(255, 255, 255));
        Nombre_Consulta7.setText("Descripcion");
        jPanel3.add(Nombre_Consulta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 170, 50));

        AñadirNegocioPersona1.setText("Añadir");
        AñadirNegocioPersona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirNegocioPersona1ActionPerformed(evt);
            }
        });
        jPanel3.add(AñadirNegocioPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        BuscarNegocios.setText("Buscar Negocios Inscritos");
        BuscarNegocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarNegociosActionPerformed(evt);
            }
        });
        jPanel3.add(BuscarNegocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 180, -1));

        Buscar_Fidu3.setText("Buscar Persona");
        Buscar_Fidu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_Fidu3ActionPerformed(evt);
            }
        });
        jPanel3.add(Buscar_Fidu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 180, -1));

        GuardarExcel.setText("Guardar .xlsx");
        GuardarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarExcelActionPerformed(evt);
            }
        });
        jPanel3.add(GuardarExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        GuardarDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "TI", "NIT", "PASAPORTE" }));
        GuardarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarDocActionPerformed(evt);
            }
        });
        jPanel3.add(GuardarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        GuardarNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        GuardarNum.setText("100001");
        GuardarNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarNumActionPerformed(evt);
            }
        });
        jPanel3.add(GuardarNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 98, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar Negocio Fiduciario", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerTablaActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_david", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM obligacion");
            ResultSet rs = pst.executeQuery();

            // Crear el modelo de la tabla con las columnas adecuadas
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Id Obligacion");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Monto");
            modelo.addColumn("Fecha Vencimiento");

            // Llenar el modelo con los datos de la consulta
            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getString("Id_obligacion");
                fila[1] = rs.getString("Descripción");
                fila[2] = rs.getString("Monto");
                fila[3] = rs.getString("Fecha_vencimiento");
                modelo.addRow(fila);
            }

            // Asignar el modelo a la JTable
            jTable2.setModel(modelo);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_VerTablaActionPerformed

    private void MontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoActionPerformed

    private void Fecha_VencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fecha_VencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fecha_VencimientoActionPerformed

    private void Registar_OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registar_OActionPerformed
        try {
            //conexion con la base de datos
            // Ruta y el nombre base de datos
            // Incluir nombre de la base de datos
            // Contraseña base de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_david","root","");
            PreparedStatement pst =cn.prepareStatement("INSERT INTO obligacion values (?,?,?,?)");

            pst.setString(1, "0");
            pst.setString(3, Monto.getText().trim());
            pst.setString(2, Descripcion_o.getText().trim());
            pst.setString(4, Fecha_Vencimiento.getText().trim());
            pst.execute();
            Monto.setText("");
            Descripcion_o.setText("");
            Descripción.setText("");
            Fecha_Vencimiento.setText("");
            Registro2.setText("Registro Exitoso");
        } catch (Exception e) {
            Registro2.setText("Fallo en el registro");
            e.printStackTrace(); //
        }
    }//GEN-LAST:event_Registar_OActionPerformed

    private void Descripcion_oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Descripcion_oActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Descripcion_oActionPerformed

    private void F_FinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_FinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_FinalActionPerformed

    private void F_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_InicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_InicioActionPerformed

    private void DescripciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripciónActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void Id_NegocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_NegocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_NegocioActionPerformed

    private void Modificar_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_NActionPerformed
        //Funcion para imprimir base de datos
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_david", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM negocio_fiduciario");
            ResultSet rs = pst.executeQuery();

            // Crear el modelo de la tabla con las columnas adecuadas
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Id_Negocio_Fiduciario");
            modelo.addColumn("Nombre");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Fecha_Inicio");
            modelo.addColumn("Fecha_Final");

            // Llenar el modelo con los datos de la consulta
            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getString("Id_Negocio_Fiduciario");
                fila[1] = rs.getString("Nombre");
                fila[2] = rs.getString("Descripción");
                fila[3] = rs.getString("Fecha_Inicio");
                fila[4] = rs.getString("Fecha_fin");
                modelo.addRow(fila);
            }

            // Asignar el modelo a la JTable
            jTable1.setModel(modelo);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Modificar_NActionPerformed

    private void Registar_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registar_NActionPerformed
        try {
            //conexion con la base de datos
            // Ruta y el nombre base de datos
            // Incluir nombre de la base de datos
            // Contraseña base de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_david","root","");
            PreparedStatement pst =cn.prepareStatement("INSERT INTO negocio_fiduciario values (?,?,?,?,?)");

            pst.setString(1, Id_Negocio.getText().trim());
            pst.setString(2, Nombre.getText().trim());
            pst.setString(3, Descripción.getText().trim());
            pst.setString(4, F_Inicio.getText().trim());
            pst.setString(5, F_Final.getText().trim());
            pst.execute();
            Id_Negocio.setText("");
            Nombre.setText("");
            Descripción.setText("");
            F_Inicio.setText("");
            F_Final.setText("");
            Registro1.setText("Registro Exitoso");
        } catch (Exception e) {
            Registro1.setText("Fallo en el registro");
            e.printStackTrace(); //
        }
    }//GEN-LAST:event_Registar_NActionPerformed

    private void Nombre_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_pActionPerformed

    private void Registar_O1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registar_O1ActionPerformed
        try {
            //conexion con la base de datos
            // Ruta y el nombre base de datos
            // Incluir nombre de la base de datos
            // Contraseña base de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_david","root","");
            PreparedStatement pst =cn.prepareStatement("INSERT INTO personas_participantes values (?,?,?,?,?)");

            pst.setString(1, "0"); //Auto Agregado
            pst.setString(2, Nombre_p.getText().trim());
            pst.setString(3, Apellido_p.getText().trim());
            pst.setString(4, (String) (TipoDoc.getSelectedItem()));
            pst.setString(5, NumID.getText().trim());
            pst.execute();
            Nombre_p.setText("");
            Nombre.setText("");
            Apellido_p.setText("");
            NumID.setText("");
            Registro3.setText("Registro Exitoso");
        } catch (Exception e) {
            Registro3.setText("Fallo en el registro");
            e.printStackTrace(); //
        }
        
        
        
        
        
    }//GEN-LAST:event_Registar_O1ActionPerformed

    private void Apellido_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido_pActionPerformed

    private void VerTabla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerTabla1ActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_david", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM personas_participantes");
            ResultSet rs = pst.executeQuery();

            // Crear el modelo de la tabla con las columnas adecuadas
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Id Personas");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido");
            modelo.addColumn("Tipo Documento");
            modelo.addColumn("Numero");

            // Llenar el modelo con los datos de la consulta
            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getString("id_persona");
                fila[1] = rs.getString("Nombre");
                fila[2] = rs.getString("Apellido");
                fila[3] = rs.getString("Tipo_Documento");
                fila[4] = rs.getString("Numero_Documento");
                modelo.addRow(fila);
            }

            // Asignar el modelo a la JTable
            jTable3.setModel(modelo);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_VerTabla1ActionPerformed

    private void TipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDocActionPerformed

    private void NumIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumIDActionPerformed

    private void Id_FiduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_FiduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_FiduActionPerformed

    private void TipoDoc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDoc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDoc1ActionPerformed

    private void Buscar_ObligacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_ObligacionActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_david", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM obligacion where Id_obligacion = ? ");
            pst.setString(1, Id_Obligacion.getText().trim());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                Des_Obligacion.setText(rs.getString("Descripción"));
            } else {
                System.out.println("fallas");
            }
                    
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_Buscar_ObligacionActionPerformed

    private void NumID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumID2ActionPerformed

    private void AñadirObligacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirObligacionActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_david", "root", "");
            PreparedStatement pst = cn.prepareStatement("INSERT INTO personas_negocios (Numero_Doc, Documento, Id_Negocio) VALUES (?, ?, ?)");
            pst.setString(1, NumID2.getText().trim());      // Número de documento
            pst.setString(2, (String) (TipoDoc.getSelectedItem()));  // Tipo de documento
            pst.setInt(3, Integer.parseInt(Id_Fidu.getText().trim()));         // ID del negocio fiduciario
            // Ejecutar la sentencia SQL
            int filasAfectadas = pst.executeUpdate();
            // Comprobar si la inserción fue exitosa
                if (filasAfectadas > 0) {
                    System.out.println("Insercion exitosa en personas_negocios.");
                    Estado_Añadir2.setText(("Insercion exitosa"));
                } else {
                    System.out.println("No se pudo insertar el registro.");
                    Estado_Añadir2.setText(("Insercion fallida"));
                }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_AñadirObligacionActionPerformed

    private void Buscar_Fidu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_Fidu2ActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_david", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM negocio_fiduciario where Id_Negocio_Fiduciario =? ");
            pst.setString(1, Id_Fidu2.getText().trim());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                Nombre_Consulta6.setText(rs.getString("Nombre"));
                Nombre_Consulta5.setText(rs.getString("Descripción"));
                Estado_Añadir1.setText(("Busqueda Correcta"));
            } else {
                Estado_Añadir1.setText(("Busqueda fallida"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Buscar_Fidu2ActionPerformed

    private void Id_ObligacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_ObligacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_ObligacionActionPerformed

    private void Id_Fidu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_Fidu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_Fidu2ActionPerformed

    private void Des_ObligacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Des_ObligacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Des_ObligacionActionPerformed

    private void ApellidoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoConsultaActionPerformed

    private void AñadirNegocioPersona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirNegocioPersona1ActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_david", "root", "");
            PreparedStatement pst = cn.prepareStatement("INSERT INTO negocio_obligacion (Id_Negocio, obligacion_ID ) VALUES (?, ?)");
            pst.setInt(1, Integer.parseInt(Id_Fidu2.getText().trim()));  
            pst.setInt(2, Integer.parseInt(Id_Obligacion.getText().trim()));  
            int filasAfectadas = pst.executeUpdate();
            if (filasAfectadas > 0) {
                    System.out.println("Insercion exitosa en personas_negocios.");
                    Estado_Añadir1.setText(("Insercion exitosa"));
                } else {
                    System.out.println("No se pudo insertar el registro.");
                    Estado_Añadir1.setText(("Insercion fallida"));
                }
        } catch (Exception e) {
            e.printStackTrace();
            Estado_Añadir1.setText(("Insercion fallida"));
        }
    }//GEN-LAST:event_AñadirNegocioPersona1ActionPerformed

    private void BuscarNegociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarNegociosActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_david", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM negocio_fiduciario where Id_Negocio_Fiduciario = ? ");
            pst.setInt(1, Integer.parseInt(Id_Fidu.getText().trim()));
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                Nombre_Consulta1.setText(rs.getString("Nombre"));
                Nombre_Consulta7.setText(rs.getString("Descripción"));
            } else {
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BuscarNegociosActionPerformed

    private void Buscar_Fidu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_Fidu3ActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_david", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM personas_participantes where Tipo_Documento =? AND Numero_Documento=? ");
            pst.setString(1, (String) (TipoDoc1.getSelectedItem()));
            pst.setString(2, NumID2.getText().trim());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                Nombre_Consulta3.setText(rs.getString("Nombre"));
                ApellidoConsulta.setText(rs.getString("Apellido"));
                Estado_Añadir2.setText("Consulta Exitosa");
            } else {
                Estado_Añadir2.setText("Consulta fallida");
                
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Buscar_Fidu3ActionPerformed

    private void GuardarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarDocActionPerformed

    private void GuardarNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarNumActionPerformed

    private void GuardarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarExcelActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_david", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT "
                + "p.Nombre, "
                + "p.Apellido, "
                + "p.Tipo_Documento, "
                + "p.Numero_Documento, "
                + "n.Id_Negocio_Fiduciario, "
                + "n.Nombre AS Negocio_Nombre, "
                + "n.Descripción, "
                + "n.Fecha_inicio, "
                + "n.Fecha_fin, "
                + "o.Id_obligacion, "
                + "o.Descripción AS Obligacion_Descripcion, "
                + "o.Monto AS Obligacion_Monto, "
                + "o.Fecha_vencimiento AS Obligacion_Fecha_Vencimiento "
                + "FROM personas_participantes p "
                + "JOIN personas_negocios pn ON p.Numero_Documento = pn.Numero_Doc AND p.Tipo_Documento = pn.Documento "
                + "JOIN negocio_obligacion n_o ON pn.Id_Negocio = n_o.Id_Negocio "
                + "JOIN obligacion o ON n_o.obligacion_ID = o.Id_obligacion "
                + "JOIN negocio_fiduciario n ON n_o.Id_Negocio = n.Id_Negocio_Fiduciario "
                + "WHERE p.Numero_Documento = ? AND p.Tipo_Documento = ?;"
            );
            
    
            pst.setString(1, GuardarNum.getText());
            pst.setString(2, (String) (GuardarDoc.getSelectedItem()));
            ResultSet rs = pst.executeQuery();
            System.out.println(rs);
 
             
            String nombreArchivo = "Resumen_Obligaciones.csv";
            File file = new File(nombreArchivo);
            PrintWriter writer = new PrintWriter(file, "UTF-8");

            // Escribir datos de la consulta
             writer.println("Nombre;Apellido;Tipo Documento;Número Documento;Id Negocio Fiduciario;Negocio Nombre;Descripción Negocio;Fecha Inicio;Fecha Fin;Id Obligación;Descripción Obligación;Monto;Fecha Vencimiento");

            // Escribir datos
            while (rs.next()) {
                writer.println(
                    rs.getString("Nombre") + ";" +
                    rs.getString("Apellido") + ";" +
                    rs.getString("Tipo_Documento") + ";" +
                    rs.getString("Numero_Documento") + ";" +
                    rs.getInt("Id_Negocio_Fiduciario") + ";" +
                    rs.getString("Negocio_Nombre") + ";" +
                    rs.getString("Descripción") + ";" +
                    rs.getDate("Fecha_inicio") + ";" +
                    rs.getDate("Fecha_fin") + ";" +
                    rs.getInt("Id_obligacion") + ";" +
                    rs.getString("Obligacion_Descripcion") + ";" +
                    rs.getDouble("Obligacion_Monto") + ";" +
                    rs.getDate("Obligacion_Fecha_Vencimiento")
                );
            }

            writer.close();
            rs.close();
            pst.close();
            cn.close();
           
            System.out.println("Archivo Excel generado exitosamente sin contraseña.");


        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_GuardarExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoConsulta;
    private javax.swing.JTextField Apellido_p;
    private javax.swing.JPanel AsignarObligaciones;
    private javax.swing.JPanel AsignarObligaciones1;
    private javax.swing.JButton AñadirNegocioPersona1;
    private javax.swing.JButton AñadirObligacion;
    private javax.swing.JButton BuscarNegocios;
    private javax.swing.JButton Buscar_Fidu2;
    private javax.swing.JButton Buscar_Fidu3;
    private javax.swing.JButton Buscar_Obligacion;
    private javax.swing.JTextField Des_Obligacion;
    private javax.swing.JTextField Descripcion_o;
    private javax.swing.JTextField Descripción;
    private javax.swing.JLabel Estado_Añadir1;
    private javax.swing.JLabel Estado_Añadir2;
    private javax.swing.JFormattedTextField F_Final;
    private javax.swing.JFormattedTextField F_Inicio;
    private javax.swing.JFormattedTextField Fecha_Vencimiento;
    private javax.swing.JComboBox<String> GuardarDoc;
    private javax.swing.JButton GuardarExcel;
    private javax.swing.JFormattedTextField GuardarNum;
    private javax.swing.JFormattedTextField Id_Fidu;
    private javax.swing.JFormattedTextField Id_Fidu2;
    private javax.swing.JTextField Id_Negocio;
    private javax.swing.JFormattedTextField Id_Obligacion;
    private javax.swing.JButton Modificar_N;
    private javax.swing.JTextField Monto;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Nombre_Consulta1;
    private javax.swing.JTextField Nombre_Consulta3;
    private javax.swing.JTextField Nombre_Consulta5;
    private javax.swing.JTextField Nombre_Consulta6;
    private javax.swing.JTextField Nombre_Consulta7;
    private javax.swing.JTextField Nombre_p;
    private javax.swing.JFormattedTextField NumID;
    private javax.swing.JFormattedTextField NumID2;
    private javax.swing.JButton Registar_N;
    private javax.swing.JButton Registar_O;
    private javax.swing.JButton Registar_O1;
    private javax.swing.JLabel Registro1;
    private javax.swing.JLabel Registro2;
    private javax.swing.JLabel Registro3;
    private javax.swing.JComboBox<String> TipoDoc;
    private javax.swing.JComboBox<String> TipoDoc1;
    private javax.swing.JButton VerTabla;
    private javax.swing.JButton VerTabla1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
